;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-kill-sexp
        backward-sexp
        c-electric-delete-forward
        c-electric-semi&comma
        completion-at-point
        easy-kill
        easy-kill-digit-argument
        easy-kill-region
        easy-mark
        end-of-buffer
        flymake-display-err-menu-for-current-line
        forward-sexp
        haskell-indentation-delete-char
        ido-switch-buffer
        indent-for-tab-command
        kill-region
        kmacro-start-macro
        magit-key-mode-popup-fetching
        magit-status
        mark-sexp
        mark-whole-buffer
        markdown-exdent-or-delete
        org-beginning-of-line
        org-ctrl-c-ctrl-c
        org-delete-char
        org-self-insert-command
        paredit-backward
        paredit-close-round
        paredit-doublequote
        paredit-forward
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-forward-slurp-sexp
        paredit-kill
        paredit-open-round
        paredit-open-square
        paredit-semicolon
        paredit-splice-sexp
        prelude-decrement-integer-at-point
        prelude-move-beginning-of-line
        sgml-slash
        smex
        sp--self-insert-command
        sp-backward-delete-char
        sp-backward-sexp
        sp-forward-sexp
        sp-forward-slurp-sexp
        sp-kill-word
        transpose-words
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        magit-discard-item
        markdown-exdent-or-delete
        ))
