;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        end-of-buffer
        flymake-display-err-menu-for-current-line
        forward-sexp
        haskell-indentation-delete-char
        kill-region
        magit-key-mode-popup-fetching
        mark-sexp
        org-delete-char
        paredit-doublequote
        paredit-forward
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-kill
        paredit-open-round
        paredit-splice-sexp
        prelude-move-beginning-of-line
        sgml-slash
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        magit-discard-item
        ))
