language: emacs-lisp
# git:
#   # deactivate ci-travis's automatic dealing with submodules when cloning - http://docs.travis-ci.com/user/build-configuration/#Git-Submodules
#   submodules: false
before_install:
  # change to public git url
  - sed -e 's/git@github.com:/http:\/\/git@github.com\//g' -i deploy.sh
  - sed -e 's/git@github.com:/http:\/\/git@github.com\//g' -i deploy-emacs.sh
  - sed -e 's/git@github.com:/http:\/\/git@github.com\//g' -i deploy-emacs-live-packs.sh
  - sed -e 's/git@github.com:/http:\/\/git@github.com\//g' -i deploy-emacs-prelude-packs.sh
  # clone the dependency on ardumont/sh as ~/bin
  - git clone git@github.com/ardumont/sh.git ~/bin
  # install ffx
  - sudo apt-get update -qq && sudo apt-get install -y firefox
  - if [ "$EMACS" = 'emacs-snapshot' ]; then
      sudo add-apt-repository -y ppa:cassou/emacs &&
      sudo apt-get update -qq &&
      sudo apt-get install -qq
          emacs-snapshot-el emacs-snapshot-gtk emacs-snapshot;
    fi
  - if [ "$EMACS" = 'emacs24' ]; then
      sudo add-apt-repository -y ppa:cassou/emacs &&
      sudo apt-get update -qq &&
      sudo apt-get install -qq
          emacs24 emacs24-el emacs24-common-non-dfsg;
    fi
  - pwd

env:
  #- EMACS=emacs
  - EMACS=emacs24
  # - EMACS=emacs-snapshot
script:
  ./run-travis-ci.sh
